name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once every day at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: YOUR_GITHUB_USERNAME
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/github-contribution-grid-snake.svg
